version: "2"

services:
   db:
     container_name: "${PROJECT_NAME}-mongodb"
     image: mongo:3.0.14
     volumes:
      - "${MONGODB_DATA_PATH}:/data/db"
     ports:
      - "27017"
     restart: always
   rabbit:
     image: rabbitmq:3.6.14
     container_name: "${PROJECT_NAME}-rabbit"
     ports:
      - "15672"
      - "5672"
     restart: always
   app-api:
     container_name: "${PROJECT_NAME}-api"
     build: ../reindex-api
     volumes:
      - "../reindex-api:/usr/src/app"
     ports:
      - "${API_HTTP_PORT}:3005"
     environment:
      - PORT=3005
      - DB_NAME=${DB_NAME}
      - RECORDS_INDEX=${RECORDS_INDEX}
      - HCATEGORIES_INDEX=${HCATEGORIES_INDEX}
      - CATEGORIES_INDEX=${CATEGORIES_INDEX}
      - HISTORY_INDEX=${HISTORY_INDEX}
      - HISTORY_TYPE=${HISTORY_TYPE}
      - ELASTIC_HOST=${PROJECT_NAME}-elasticsearch
      - RABBITMQ_HOST=${PROJECT_NAME}-rabbit
      - DB_PORT_27017_TCP_ADDR=${PROJECT_NAME}-mongodb
     restart: always
   elasticsearch:
     container_name: "${PROJECT_NAME}-elasticsearch"
     image: elasticsearch:2.4.2
     ports:
       - "9200"
     volumes:
      - "${ELASTIC_DATA_PATH}:/usr/share/elasticsearch/data"
     restart: always
   app:
     container_name: "${PROJECT_NAME}-app"
     build: .
     volumes: 
      - "./src:/usr/src/app/src"
     ports:
      - "${APP_HTTP_PORT}:3000"
     environment:
      - API_URL=http://${PROJECT_NAME}-api:3005
     restart: always
     


